project:
  type: book

book:
  title: "Automated Testing in R"
  author: "Jakub Sobolewski"
  date: "01/1/2025"
  google-analytics: "G-735BLDHJRX"
  repo-url: https://github.com/jakubsob/automated-testing-in-r/
  page-footer:
    border: true
    center: "Copyright 2025, Jakub Sobolewski"
    right:
      - icon: github
        href: https://github.com/jakubsob
      - icon: linkedin
        href: https://www.linkedin.com/in/jakub-sobolewski-r/
  sidebar:
    style: floating
    collapse-level: 2

  chapters:
    - index.qmd

format:
  html:
    theme:
      - brand
    code-copy: true
  pdf:
    documentclass: scrreprt
