project:
  type: book

website:
  announcement:
    icon: info-circle
    dismissable: true
    content: "This book is a work in progress. 🚧 Visit my <a href='https://jakubsob.github.io/blog' target='_blank'>blog</a>"
    type: warning
    position: below-navbar

book:
  title: "Automated Testing in R"
  author: "Jakub Sobolewski"
  date: "01/1/2025"
  google-analytics: "G-735BLDHJRX"
  repo-url: https://github.com/jakubsob/automated-testing-in-r/

  page-footer:
    border: true
    center: "Automated Testing in R © 2025 by Jakub Sobolewski is licensed under CC BY-NC-ND 4.0"
    right:
      - icon: github
        href: https://github.com/jakubsob
      - icon: linkedin
        href: https://www.linkedin.com/in/jakub-sobolewski-r/
  sidebar:
    style: floating
    collapse-level: 2

  chapters:
    - index.qmd
    - part: "Testing fundamentals"
      chapters:
      - anatomy-of-a-test.qmd
      - types-of-tests.qmd

brand:
  dark: _brand_dark.yml
  light: _brand.yml

format:
  html:
    code-copy: true
    code-line-numbers: true
  pdf:
    documentclass: scrreprt
